### ISSUE TITLE
Rule request: require `<html>` tag to have `lang` attribute

### ISSUE THREAD

**Issue by MelSumner** [ember-template-lint/ember-template-lint#1314]
Completion of issue #1230 will add the ability to lint .html files. Specifically, the `index.html` file is the desired target for this rule. 

## Tasks 
1. [ ] Add a new rule called `require-valid-language` (or similar) 
1. [ ] the rule should check the `<html>` element for the presence of the `lang` attribute
1. [ ] it should allow lang tags (such as `en`, `fr`, etc) and region subtags (`en-us`, etc)
1. [ ] it should allow internationalized syntax
1. [ ] it should disallow non-valid language or region values
1. [ ] it should not conflict with the `ember-intl` addon syntax

**Comment by Turbo87** [comment]
Resolved by #1386
