### ISSUE TITLE
Plan for v3.0 Release

### ISSUE THREAD

**Issue by MelSumner** [ember-template-lint/ember-template-lint#1315]
The last major release was [V2](https://github.com/ember-template-lint/ember-template-lint/releases/tag/v2.0.0) in 2020-02-22.

List of breaking changes to include:

* [x] [Drop Node 13 support](https://github.com/ember-template-lint/ember-template-lint/issues/1444)
* [x] Remove old items from `lib/helpers/deprecated-rules.js`
* [x] Include support for linting .html files (#1232 )
* [x] Update `catchNonexistentRoles` option to default to `true` in [no-invalid-role](https://github.com/ember-template-lint/ember-template-lint/blob/master/docs/rule/no-invalid-role.md)
* [x] Update `noImplicitThis` option default to true and `requireDash` option default to false in `no-curly-component-invocation` rule (#1642)
* [x] Update rule to default to `strict` behavior in [link-rel-noopener](https://github.com/ember-template-lint/ember-template-lint/blob/master/docs/rule/link-rel-noopener.md)
* [x] New stylistic rules (#1638) (see current list of rules [here](https://github.com/ember-template-lint/ember-template-lint/blob/master/lib/config/stylistic.js)):
   * [modifier-name-case](https://github.com/ember-template-lint/ember-template-lint/blob/master/docs/rule/modifier-name-case.md)
   * [no-whitespace-for-layout](https://github.com/ember-template-lint/ember-template-lint/blob/master/docs/rule/no-whitespace-for-layout.md)
   * [no-whitespace-within-word](https://github.com/ember-template-lint/ember-template-lint/blob/master/docs/rule/no-whitespace-within-word.md)
* [x] Promote all `octane` rules to the `recommended` config (and delete the `octane` config) since all supported Ember LTS versions are Ember Octane now (3.16, 3.20, 3.24) (#1639)
* [x] New recommended rules (#1643) (see current list of rules [here](https://github.com/ember-template-lint/ember-template-lint#rules)):
   * [builtin-component-arguments](https://github.com/ember-template-lint/ember-template-lint/blob/master/docs/rule/builtin-component-arguments.md)
   * [deprecated-each-syntax](https://github.com/ember-template-lint/ember-template-lint/blob/master/docs/rule/deprecated-each-syntax.md)
   * [deprecated-inline-view-helper](https://github.com/ember-template-lint/ember-template-lint/blob/master/docs/rule/deprecated-inline-view-helper.md)
  * [no-accesskey-attribute](https://github.com/ember-template-lint/ember-template-lint/blob/master/docs/rule/no-accesskey-attribute.md)
   * [no-arguments-for-html-elements](https://github.com/ember-template-lint/ember-template-lint/blob/master/docs/rule/no-arguments-for-html-elements.md)
   * [no-aria-hidden-body](https://github.com/ember-template-lint/ember-template-lint/blob/master/docs/rule/no-aria-hidden-body.md)
   * [no-block-params-for-html-elements](https://github.com/ember-template-lint/ember-template-lint/blob/master/docs/rule/no-block-params-for-html-elements.md)
   * [no-duplicate-id](https://github.com/ember-template-lint/ember-template-lint/blob/master/docs/rule/no-duplicate-id.md)
   * [no-duplicate-landmark-elements](https://github.com/ember-template-lint/ember-template-lint/blob/master/docs/rule/no-duplicate-landmark-elements.md)
   * [no-forbidden-elements](https://github.com/ember-template-lint/ember-template-lint/blob/master/docs/rule/no-forbidden-elements.md)
   * [no-heading-inside-button](https://github.com/ember-template-lint/ember-template-lint/blob/master/docs/rule/no-heading-inside-button.md)
   * [no-invalid-block-param-definition](https://github.com/ember-template-lint/ember-template-lint/blob/master/docs/rule/no-invalid-block-param-definition.md)
   * [no-invalid-link-title](https://github.com/ember-template-lint/ember-template-lint/blob/master/docs/rule/no-invalid-link-title.md) - prevents the same text being used for the link and for the title attribute value. 
   * [no-nested-landmark](https://github.com/ember-template-lint/ember-template-lint/blob/master/docs/rule/no-nested-landmark.md)
   * [no-nested-splattributes](https://github.com/ember-template-lint/ember-template-lint/blob/master/docs/rule/no-nested-splattributes.md)
   * [no-passed-in-event-handlers](https://github.com/ember-template-lint/ember-template-lint/blob/master/docs/rule/no-passed-in-event-handlers.md)
   * [no-positional-data-test-selectors](https://github.com/ember-template-lint/ember-template-lint/blob/master/docs/rule/no-positional-data-test-selectors.md)
   * [no-potential-path-strings](https://github.com/ember-template-lint/ember-template-lint/blob/master/docs/rule/no-potential-path-strings.md)
   * [no-redundant-fn](https://github.com/ember-template-lint/ember-template-lint/blob/master/docs/rule/no-redundant-fn.md)
   * [no-redundant-landmark-role](https://github.com/ember-template-lint/ember-template-lint/blob/master/docs/rule/no-redundant-landmark-role.md)
   * [no-unbalanced-curlies](https://github.com/ember-template-lint/ember-template-lint/blob/master/docs/rule/no-unbalanced-curlies.md)
   * [no-yield-only](https://github.com/ember-template-lint/ember-template-lint/blob/master/docs/rule/no-yield-only.md)
   * [require-input-label](https://github.com/ember-template-lint/ember-template-lint/blob/master/docs/rule/require-input-label.md) - requires input elements to have associated labels. The rule is a bit permissive (because it has to be in this context) but it should catch common instances of this issue. 
  * [require-lang-attribute](https://github.com/ember-template-lint/ember-template-lint/blob/master/docs/rule/require-lang-attribute.md)
  * [splat-attributes-only](https://github.com/ember-template-lint/ember-template-lint/blob/master/docs/rule/splat-attributes-only.md)
* [x] Fix newly-introduced bug with rule configurations https://github.com/ember-template-lint/ember-template-lint/issues/1644
* [x] Rules override is reversed on extends #1417 
* [x] In linter.js: `TODO: deprecate moduleId and moduleName` Related issue: https://github.com/ember-template-lint/ember-template-lint/issues/1346 
* [x] Remove automatic TextNode unwrapping in `AstNodeInfo.elementAttributeValue` #1358 (PR #1388)
* [x] Feature: deprecate `pending` & replace with `todo` #1557 
* [x] Deprecate passing `classNames` and `classNameBindings` as an argument to component invocation https://github.com/ember-template-lint/ember-template-lint/issues/1762

Final check before release: 
* [ ] make sure all rulesets are updated
* [ ] double check recommended ruleset

**Comment by Turbo87** [comment]
we could consider having a `next` preset where we gather all the rules that are supposed to go in the next major

**Comment by MelSumner** [comment]
> we could consider having a `next` preset where we gather all the rules that are supposed to go in the next major

I like this idea.

**Comment by MelSumner** [comment]
> Ya, we definitely do need to evaluate the recommended / octane sets for the next major. I think these are good but I think we'll need to do a more thorough review as we lead up.

Def isn't meant to be exhaustive, just put somewhere so I don't forget. :) If it's convenient, we can edit this list as we go.

**Comment by bmish** [comment]
Hey folks, I updated this ticket description to include a lot more breaking changes.

**Comment by MelSumner** [comment]
@rwjblue do we think we're just about ready for this?

**Comment by rwjblue** [comment]
We need to deal with https://github.com/ember-template-lint/ember-template-lint/issues/1417 first

**Comment by Turbo87** [comment]
now that https://github.com/ember-template-lint/ember-template-lint/issues/1417 is fixed, I suppose we're ready to release? if I don't hear any objections I'll get a new major released on Friday.

**Comment by bmish** [comment]
I updated this ticket to list a lot more rules that we should enable in our various presets. Would be good for someone else to double-check that we haven't missed any rules that should be added, or added any rules that shouldn't be added.

**Comment by rwjblue** [comment]
Thanks @bmish! I'll try to run through those updates / suggestions this weekend...

**Comment by bmish** [comment]
I added another item to checklist for this ticket since we are only weeks away from all supported Ember LTS versions being on Octane:

>  Promote all `octane` rules to the `recommended` config (and delete the `octane` config) since all supported Ember LTS versions are Ember Octane now (3.16, 3.20, 3.24)

**Comment by rwjblue** [comment]
Ya, sounds good to me.

**Comment by bmish** [comment]
Heads up, I completed several of the tasks in the list, and added a few more tasks to complete. Would be nice to complete this release soon.

**Comment by MelSumner** [comment]
I've updated the issue with all the tasks that need doing; I think we could release in the next week or two with concentrated effort. 👍

**Comment by scalvert** [comment]
@rwjblue @MelSumner I've resolved all the remaining issues pending for the v3 release. I think we're ready to go.

**Comment by bmish** [comment]
I noticed there's one issue that hasn't actually been completed:

```
Update rule to default to `strict` behavior in link-rel-noopener
```

But we could also skip this unless someone feels strongly about completing it.

Looking to getting the release out!

**Comment by rwjblue** [comment]
> I noticed there's one issue that hasn't actually been completed:
>
> Update rule to default to `strict` behavior in link-rel-noopener

We changed the recommended value for this:

https://github.com/ember-template-lint/ember-template-lint/blob/2e921e309147fa784894040617cc538f0c9b8b64/lib/config/recommended.js#L10

**Comment by bmish** [comment]
@rwjblue I see. I think it's generally better to change the default in the rule itself, but that works for now.

**Comment by scalvert** [comment]
https://github.com/ember-template-lint/ember-template-lint/releases/tag/v3.0.0
